### ISSUE TITLE
Timing attack possible in Bcrypt.checkpw?

### ISSUE THREAD

**Issue by phxql** [jeremyh/jBCrypt#3]
Hello,

i'm not sure about this, but maybe you can examine it: Is `Bcrypt.checkpw` vulnerable to a timing attack? It uses `String.compareTo` to compare the two hashes, and this method is vulnerable to timing attacks (at least in my java implementation, as it returns when the first non-equal character is found).

**Comment by MadaraUchiha** [comment]
This seems to be resolved long ago. Can this ticket be closed?

**Comment by phxql** [comment]
Yep, has been resolved.
